### ISSUE TITLE
RuntimeError: Failed to add edge detection

### ISSUE THREAD

**Issue by Cronos512** [sbcshop/Rotary_HAT_for_RaspberryPi_Software#1]
When running example with touch functions, I get the following error : 

Rotary_HAT_for_RaspberryPi_Software/example $ python face.py 
Traceback (most recent call last):
  File "/home/thierry/Rotary_HAT_for_RaspberryPi_Software/example/face.py", line 25, in <module>
    touch.int_irq(Callback)
  File "/home/thierry/Rotary_HAT_for_RaspberryPi_Software/example/../lib/Round_Touch.py", line 46, in int_irq
    self.GPIO.add_event_detect(self.TP_INT,self.GPIO.FALLING,Int_Callback,5) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to add edge detection

SPI & I2C is enabled.

**Comment by EricRobillard** [comment]
Install lgpio: sudo apt-get -y install python3-rpi.lgpio.
It's run on RPI 4b
